name: feuerwehrstatus
description: Zeigt Einsätze der Oberösterreichischen Feuerwehr und gibt Statusmeldungen durch
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  auto_size_text: ^3.0.0
  overlay_support: ^2.1.0
  blur: ^3.1.0
  window_manager: ^0.3.5
  flutter_native_splash: ^2.3.1
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.18.1
  maps_launcher: ^2.2.0
  url_launcher: ^6.1.12
  map_launcher: ^2.5.0+1
  google_maps_flutter: ^2.4.0
  google_maps_flutter_android: ^2.4.16
  google_maps_flutter_ios: ^2.2.3
  google_maps_flutter_platform_interface: ^2.4.0
  onesignal_flutter: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FF0000"
  image: assets/fflogo_splash.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appicons/ic_launcher.png"
  adaptive_icon_background: "assets/appicons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/appicons/ic_launcher_foreground.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
